sound: soc: phytium_i2s: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
sound/soc/phytium/phytium_i2s.c:1421:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
 1421 |         .remove = phytium_i2s_remove,
      |                   ^~~~~~~~~~~~~~~~~~
sound/soc/phytium/phytium_i2s.c:1421:19: note: (near initialization for ‘phytium_i2s_driver.<anonymous>.remove’)