mmc: phytium-sdci: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/mmc/host/phytium-sdci.c:1426:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
 1426 |         .remove = phytium_sdci_remove,
      |                   ^~~~~~~~~~~~~~~~~~~
drivers/mmc/host/phytium-sdci.c:1426:19: note: (near initialization for ‘phytium_sdci_driver.<anonymous>.remove’)